name: Umi Digital
favicon: null
layout_spectrum: 0.32972
typography_spectrum: 0.72801
title: The best website company for hotels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#14162d'
    - '#dbcab6'
    - '#81524a'
    - '#998779'
    - '#caa68a'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
