name: Umi Digital
favicon: null
layout_spectrum: 0.3291638968512416
typography_spectrum: 0.9250032457057387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6725455496925861
  lightness: 0.4192056250758469
  saturation: 0.3152304363902658
  rhythmicContrast: 0.06003370019607246
purpose: []
