name: Umi Digital
favicon: null
layout_spectrum: 0.87841
typography_spectrum: 0.41415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35b5e6'
    - '#00ffff'
    - '#0080ff'
    - '#0000ff'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
